START TRANSACTION;

CREATE TABLE "Platforms" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Name" character varying(1000) NOT NULL,
    CONSTRAINT "PK_Platforms" PRIMARY KEY ("Id")
);

CREATE INDEX "IX_Platforms_Id" ON "Platforms" ("Id");

COMMIT;

