START TRANSACTION;

CREATE TABLE "Facilities" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Name" character varying(1000) NOT NULL,
    "StreetAddress" character varying(1000) NOT NULL,
    "City" character varying(100) NOT NULL,
    "ZipCode" character varying(20) NOT NULL,
    "Latitude" numeric(18,2) NOT NULL,
    "Longitude" numeric(18,2) NOT NULL,
    "PhoneNumber" character varying(100) NOT NULL,
    "MailingAddress" character varying(1000) NOT NULL,
    "MailingCity" character varying(1000) NOT NULL,
    "MailingZipCode" character varying(20) NOT NULL,
    "Fax" character varying(100) NOT NULL,
    "BillingName" character varying(1000) NOT NULL,
    "WebsiteLink" character varying(1000) NOT NULL,
    "BedSize" integer NOT NULL,
    "AutoOffer" boolean NOT NULL,
    "AcceptsTravelers" boolean NOT NULL,
    "SupplementalNursingOverride" boolean NOT NULL,
    "IsAdvancedPractice" boolean NOT NULL,
    "PermanentNote" character varying(8000) NOT NULL,
    "PayrollBillingNote" character varying(2000) NOT NULL,
    "LastWorkOrderDate" timestamp with time zone NOT NULL,
    "LastNoteDate" timestamp with time zone NOT NULL,
    "StateId" integer,
    "MailingStateId" integer,
    "DoNotRehireReason" character varying(1000) NOT NULL,
    CONSTRAINT "PK_Facilities" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Facilities_States_MailingStateId" FOREIGN KEY ("MailingStateId") REFERENCES "States" ("Id"),
    CONSTRAINT "FK_Facilities_States_StateId" FOREIGN KEY ("StateId") REFERENCES "States" ("Id")
);

CREATE TABLE "Jobs" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "JobTitle" character varying(1000),
    "UniqueNotes" character varying(8000),
    "PlatformJobId" character varying(100),
    "JobStatus" integer,
    "JobType" integer,
    "HousingProvided" boolean NOT NULL,
    "HideExternally" boolean NOT NULL,
    "ContractLengthWeeks" integer NOT NULL,
    "StartDate" timestamp with time zone NOT NULL,
    "ExpiresOn" timestamp with time zone NOT NULL,
    "RepostedOn" timestamp with time zone NOT NULL,
    "ClientManagerId" integer,
    "FacilityId" integer,
    "DisciplineId" integer,
    "SpecialtyId" integer,
    "IsFellowshipRequired" boolean NOT NULL,
    "JobStrength" numeric(18,2) NOT NULL,
    "HideCity" boolean NOT NULL,
    "AutoPosted" boolean NOT NULL,
    "AllowsAutoposterUpdate" boolean NOT NULL,
    "Requirements" character varying(8000),
    "IsNoContractInHandOnCreation" boolean NOT NULL,
    "SyncToSense" boolean NOT NULL,
    "LastSyncToSense" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_Jobs" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Jobs_Disciplines_DisciplineId" FOREIGN KEY ("DisciplineId") REFERENCES "Disciplines" ("Id"),
    CONSTRAINT "FK_Jobs_Facilities_FacilityId" FOREIGN KEY ("FacilityId") REFERENCES "Facilities" ("Id")
);

CREATE TABLE "JobSubSpecialties" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "JobId" integer NOT NULL,
    "SubSpecialtyId" integer NOT NULL,
    "IsRequired" boolean NOT NULL,
    CONSTRAINT "PK_JobSubSpecialties" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_JobSubSpecialties_Jobs_JobId" FOREIGN KEY ("JobId") REFERENCES "Jobs" ("Id") ON DELETE CASCADE
);

CREATE INDEX "IX_Facilities_Id" ON "Facilities" ("Id");

CREATE INDEX "IX_Facilities_MailingStateId" ON "Facilities" ("MailingStateId");

CREATE INDEX "IX_Facilities_StateId" ON "Facilities" ("StateId");

CREATE INDEX "IX_Jobs_DisciplineId" ON "Jobs" ("DisciplineId");

CREATE INDEX "IX_Jobs_FacilityId" ON "Jobs" ("FacilityId");

CREATE INDEX "IX_Jobs_Id" ON "Jobs" ("Id");

CREATE INDEX "IX_JobSubSpecialties_Id" ON "JobSubSpecialties" ("Id");

CREATE INDEX "IX_JobSubSpecialties_JobId" ON "JobSubSpecialties" ("JobId");

COMMIT;

