START TRANSACTION;

CREATE TABLE "Disciplines" (
                               "Id" integer GENERATED BY DEFAULT AS IDENTITY,
                               "Abbreviation" character varying(10) NOT NULL,
                               "Name" character varying(500) NOT NULL,
                               "IsForProvider" boolean NOT NULL,
                               CONSTRAINT "PK_Disciplines" PRIMARY KEY ("Id")
);

CREATE TABLE "Specialties" (
                               "Id" integer GENERATED BY DEFAULT AS IDENTITY,
                               "Name" character varying(1000) NOT NULL,
                               "Description" character varying(4000) NOT NULL,
                               "IsActive" boolean NOT NULL,
                               CONSTRAINT "PK_Specialties" PRIMARY KEY ("Id")
);

CREATE TABLE "States" (
                          "Id" integer GENERATED BY DEFAULT AS IDENTITY,
                          "Name" character varying(100) NOT NULL,
                          "Abbreviation" character varying(3) NOT NULL,
                          CONSTRAINT "PK_States" PRIMARY KEY ("Id")
);

CREATE TABLE "DisciplineSpecialties" (
                                         "Id" integer GENERATED BY DEFAULT AS IDENTITY,
                                         "DisciplineId" integer NOT NULL,
                                         "SpecialtyId" integer NOT NULL,
                                         CONSTRAINT "PK_DisciplineSpecialties" PRIMARY KEY ("Id"),
                                         CONSTRAINT "FK_DisciplineSpecialties_Disciplines_DisciplineId" FOREIGN KEY ("DisciplineId") REFERENCES "Disciplines" ("Id") ON DELETE CASCADE,
                                         CONSTRAINT "FK_DisciplineSpecialties_Specialties_SpecialtyId" FOREIGN KEY ("SpecialtyId") REFERENCES "Specialties" ("Id") ON DELETE CASCADE
);

CREATE TABLE "SubSpecialties" (
                                  "Id" integer GENERATED BY DEFAULT AS IDENTITY,
                                  "Name" character varying(1000) NOT NULL,
                                  "HasFellowShip" boolean,
                                  "SpecialtyId" integer NOT NULL,
                                  CONSTRAINT "PK_SubSpecialties" PRIMARY KEY ("Id"),
                                  CONSTRAINT "FK_SubSpecialties_Specialties_SpecialtyId" FOREIGN KEY ("SpecialtyId") REFERENCES "Specialties" ("Id") ON DELETE CASCADE
);

CREATE TABLE "Providers" (
                             "Id" integer GENERATED BY DEFAULT AS IDENTITY,
                             "PreferredFirstName" character varying(1000) NOT NULL,
                             "FirstName" character varying(1000) NOT NULL,
                             "LastName" character varying(1000) NOT NULL,
                             "MaidenName" character varying(1000) NOT NULL,
                             "PrimaryPhoneNumber" character varying(200) NOT NULL,
                             "AlternativePhoneNumber" character varying(200) NOT NULL,
                             "IsPrimaryPhoneNumberInService" boolean NOT NULL,
                             "IsAlternativePhoneNumberInService" boolean NOT NULL,
                             "Email" character varying(1000) NOT NULL,
                             "AlternateEmail" character varying(1000) NOT NULL,
                             "DateOfBirth" timestamp with time zone NOT NULL,
                             "Ssn" character varying(200),
                             "LastFourSsn" character varying(4) NOT NULL,
                             "PaycomEeCode" character varying(10) NOT NULL,
                             "UserId" uuid NOT NULL,
                             "Username" character varying(128) NOT NULL,
                             "StreetAddress" character varying(1000) NOT NULL,
                             "City" character varying(300) NOT NULL,
                             "StateId" integer,
                             "ZipCode" character varying(200) NOT NULL,
                             "TemporaryStreetAddress" character varying(1000) NOT NULL,
                             "TemporaryCity" character varying(200) NOT NULL,
                             "TemporaryStateId" integer,
                             "TemporaryZipCode" character varying(200) NOT NULL,
                             "AvailabilityDate" timestamp with time zone NOT NULL,
                             "ReferredBy" character varying(2000) NOT NULL,
                             "ReferralDate" timestamp with time zone NOT NULL,
                             "SensitiveDataModifiedOn" timestamp with time zone NOT NULL,
                             "ForceNextLogout" boolean NOT NULL,
                             "TravelerId" integer,
                             "LastRecruiterId" integer,
                             "DisciplineId" integer,
                             "IsPriority" boolean NOT NULL,
                             CONSTRAINT "PK_Providers" PRIMARY KEY ("Id"),
                             CONSTRAINT "FK_Providers_Disciplines_DisciplineId" FOREIGN KEY ("DisciplineId") REFERENCES "Disciplines" ("Id"),
                             CONSTRAINT "FK_Providers_States_StateId" FOREIGN KEY ("StateId") REFERENCES "States" ("Id"),
                             CONSTRAINT "FK_Providers_States_TemporaryStateId" FOREIGN KEY ("TemporaryStateId") REFERENCES "States" ("Id")
);

CREATE INDEX "IX_Disciplines_Id" ON "Disciplines" ("Id");

CREATE INDEX "IX_DisciplineSpecialties_DisciplineId" ON "DisciplineSpecialties" ("DisciplineId");

CREATE INDEX "IX_DisciplineSpecialties_Id" ON "DisciplineSpecialties" ("Id");

CREATE INDEX "IX_DisciplineSpecialties_SpecialtyId" ON "DisciplineSpecialties" ("SpecialtyId");

CREATE INDEX "IX_Providers_DisciplineId" ON "Providers" ("DisciplineId");

CREATE INDEX "IX_Providers_FirstName_LastName" ON "Providers" ("FirstName", "LastName");

CREATE INDEX "IX_Providers_Id" ON "Providers" ("Id");

CREATE INDEX "IX_Providers_StateId" ON "Providers" ("StateId");

CREATE INDEX "IX_Providers_TemporaryStateId" ON "Providers" ("TemporaryStateId");

CREATE INDEX "IX_Specialties_Id" ON "Specialties" ("Id");

CREATE INDEX "IX_States_Id" ON "States" ("Id");

CREATE INDEX "IX_SubSpecialties_Id" ON "SubSpecialties" ("Id");

CREATE INDEX "IX_SubSpecialties_SpecialtyId" ON "SubSpecialties" ("SpecialtyId");

COMMIT;

